stages:
  - "Build"

##
## Build
##
build:
  stage: "Build"
  image: node:latest
  script:
    - npm install
    - node -e 'require("./run").init()'
  artifacts:
    expire_in: 1 week
    paths:
      - bin/